# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
minecraft_version=26.3
yarn_mappings=26.3+build.6
loader_version=0.16.5

# Mod Properties
mod_version = 1.0
maven_group = crqzycat
archives_base_name = Maintena

# Dependencies
fabric_version=0.110.1+26.3